import { spawn } from "node:child_process";
import { Readable } from "node:stream";
import type { ReadableStream as NodeReadableStream } from "node:stream/web";

type CommandResult = {
  stdout: string;
  stderr: string;
};

export type PetyrDatabaseRestoreResult = {
  ok: true;
  durationMs: number;
  fileName: string;
  fileSize: number;
  stderrTail: string | null;
};

const MAX_LOG_CHARS = 12000;

function appendLimited(current: string, next: Buffer) {
  const combined = current + next.toString("utf8");
  return combined.length > MAX_LOG_CHARS ? combined.slice(combined.length - MAX_LOG_CHARS) : combined;
}

function getDatabaseUrl() {
  const value = process.env.DATABASE_URL?.trim();
  if (!value) {
    throw new Error("DATABASE_URL is not configured.");
  }

  return value;
}

function getPostgresCliDatabaseUrl() {
  const value = getDatabaseUrl();

  try {
    const url = new URL(value);
    url.searchParams.delete("schema");
    return url.toString();
  } catch {
    return value;
  }
}

function runCommand(command: string, args: string[]): Promise<CommandResult> {
  return new Promise((resolve, reject) => {
    const child = spawn(command, args, {
      env: process.env,
      windowsHide: true
    });
    let stdout = "";
    let stderr = "";

    child.stdout.on("data", (chunk: Buffer) => {
      stdout = appendLimited(stdout, chunk);
    });
    child.stderr.on("data", (chunk: Buffer) => {
      stderr = appendLimited(stderr, chunk);
    });
    child.on("error", reject);
    child.on("close", (code) => {
      if (code === 0) {
        resolve({ stdout, stderr });
        return;
      }

      reject(new Error(`${command} exited with code ${code}: ${stderr || stdout || "no output"}`));
    });
  });
}

export async function assertPostgresCliAvailable(command: "pg_dump" | "psql") {
  await runCommand(command, ["--version"]);
}

export function createPetyrDatabaseBackupStream() {
  const databaseUrl = getPostgresCliDatabaseUrl();
  const child = spawn(
    "pg_dump",
    [
      "--dbname",
      databaseUrl,
      "--clean",
      "--if-exists",
      "--no-owner",
      "--no-privileges",
      "--format",
      "plain"
    ],
    {
      env: process.env,
      windowsHide: true
    }
  );
  let stderr = "";

  const stream = new ReadableStream<Uint8Array>({
    start(controller) {
      child.stdout.on("data", (chunk: Buffer) => {
        controller.enqueue(new Uint8Array(chunk));
      });
      child.stderr.on("data", (chunk: Buffer) => {
        stderr = appendLimited(stderr, chunk);
      });
      child.on("error", (error) => {
        controller.error(error);
      });
      child.on("close", (code) => {
        if (code === 0) {
          controller.close();
          return;
        }

        controller.error(new Error(`pg_dump exited with code ${code}: ${stderr || "no output"}`));
      });
    },
    cancel() {
      child.kill("SIGTERM");
    }
  });

  return stream;
}

export async function restorePetyrDatabaseBackup(file: File): Promise<PetyrDatabaseRestoreResult> {
  await assertPostgresCliAvailable("psql");

  if (!file.name.toLowerCase().endsWith(".sql")) {
    throw new Error("Database restore accepts only .sql files generated by the Petyr backup export.");
  }

  const startedAt = Date.now();
  const databaseUrl = getPostgresCliDatabaseUrl();

  return new Promise((resolve, reject) => {
    const child = spawn("psql", ["--set", "ON_ERROR_STOP=1", "--dbname", databaseUrl], {
      env: process.env,
      windowsHide: true
    });
    let stdout = "";
    let stderr = "";

    child.stdout.on("data", (chunk: Buffer) => {
      stdout = appendLimited(stdout, chunk);
    });
    child.stderr.on("data", (chunk: Buffer) => {
      stderr = appendLimited(stderr, chunk);
    });
    child.on("error", reject);
    child.on("close", (code) => {
      if (code === 0) {
        resolve({
          ok: true,
          durationMs: Date.now() - startedAt,
          fileName: file.name,
          fileSize: file.size,
          stderrTail: stderr.trim() ? stderr : null
        });
        return;
      }

      reject(new Error(`psql restore exited with code ${code}: ${stderr || stdout || "no output"}`));
    });

    const source = Readable.fromWeb(file.stream() as unknown as NodeReadableStream<Uint8Array>);
    source.on("error", (error) => {
      child.stdin.destroy(error);
    });
    child.stdin.on("error", (error: NodeJS.ErrnoException) => {
      if (error.code !== "EPIPE") {
        reject(error);
      }
    });
    source.pipe(child.stdin);
  });
}

export function createPetyrDatabaseBackupFileName(now = new Date()) {
  const stamp = now.toISOString().replace(/[-:]/g, "").replace(/\.\d{3}Z$/, "Z");
  return `petyr-postgres-backup-${stamp}.sql`;
}
