export type EditableForecastType = "previous_month" | "ongoing";

export type ForecastEntryTarget = EditableForecastType | "ai_forecast" | "actuals";

export type ForecastEntryMode = {
  editable: boolean;
  editableForecastType: EditableForecastType | null;
  label: string;
  reason: string;
  locked: boolean;
};

export type ForecastEntryModeParams = {
  year: number;
  month: number; // 1-12
  currentDate?: Date;
  forecastType?: ForecastEntryTarget;
};

type ForecastEntryModeExpectation = Pick<ForecastEntryMode, "editable" | "editableForecastType" | "locked">;

type ForecastEntryModeDiagnosticCase = {
  name: string;
  params: Required<Pick<ForecastEntryModeParams, "year" | "month" | "currentDate">> & {
    forecastType?: ForecastEntryTarget;
  };
  expected: ForecastEntryModeExpectation;
};

function buildMode(input: Omit<ForecastEntryMode, "locked">): ForecastEntryMode {
  return {
    ...input,
    locked: !input.editable
  };
}

function buildLockedMode(input: Omit<ForecastEntryMode, "editable" | "locked">): ForecastEntryMode {
  return {
    ...input,
    editable: false,
    locked: true
  };
}

function formatForecastType(forecastType: EditableForecastType | null) {
  if (forecastType === "ongoing") return "ongoing forecast";
  if (forecastType === "previous_month") return "previous-month forecast";
  return "forecast";
}

function resolveMonthLevelMode(params: ForecastEntryModeParams): ForecastEntryMode {
  const currentDate = params.currentDate ?? new Date();
  const currentYear = currentDate.getFullYear();
  const currentMonth = currentDate.getMonth() + 1;
  const currentDay = currentDate.getDate();

  if (!Number.isInteger(params.year) || !Number.isInteger(params.month) || params.month < 1 || params.month > 12) {
    return buildLockedMode({
      editableForecastType: null,
      label: "Invalid forecast month",
      reason: "Forecast entry requires a valid year and a month between 1 and 12."
    });
  }

  if (!Number.isFinite(currentYear) || !Number.isFinite(currentMonth) || !Number.isFinite(currentDay)) {
    return buildLockedMode({
      editableForecastType: null,
      label: "Invalid current date",
      reason: "Forecast entry requires a valid current date before editability can be resolved."
    });
  }

  const isPast = params.year < currentYear || (params.year === currentYear && params.month < currentMonth);
  const isCurrent = params.year === currentYear && params.month === currentMonth;
  const isFuture = params.year > currentYear || (params.year === currentYear && params.month > currentMonth);

  if (isPast) {
    return buildLockedMode({
      editableForecastType: null,
      label: "Read-only month",
      reason: "Past months are locked and cannot be edited."
    });
  }

  if (isCurrent && currentDay <= 15) {
    return buildMode({
      editable: true,
      editableForecastType: "previous_month",
      label: "Edit previous-month forecast",
      reason: "Until the 15th included, the CSM can edit the previous-month forecast for the current month."
    });
  }

  if (isCurrent && currentDay > 15) {
    return buildMode({
      editable: true,
      editableForecastType: "ongoing",
      label: "Edit ongoing forecast",
      reason: "From the 16th onward, only the ongoing forecast is editable for the current month."
    });
  }

  if (isFuture) {
    return buildMode({
      editable: true,
      editableForecastType: "previous_month",
      label: "Edit future previous-month forecast",
      reason: "Future months can be planned through the previous-month forecast field."
    });
  }

  return buildLockedMode({
    editableForecastType: null,
    label: "Not editable",
    reason: "No editing rule matched this month."
  });
}

export function getForecastEntryMode(params: ForecastEntryModeParams): ForecastEntryMode {
  const monthMode = resolveMonthLevelMode(params);

  if (!params.forecastType || !monthMode.editable) return monthMode;

  if (params.forecastType === "ai_forecast") {
    return buildLockedMode({
      editableForecastType: monthMode.editableForecastType,
      label: "AI forecast locked",
      reason: "AI forecast is generated by Petyr and is never editable."
    });
  }

  if (params.forecastType === "actuals") {
    return buildLockedMode({
      editableForecastType: monthMode.editableForecastType,
      label: "Closed revenue locked",
      reason: "Closed revenue comes from Redash-derived data and is never editable in Forecast Entry."
    });
  }

  if (params.forecastType !== monthMode.editableForecastType) {
    return buildLockedMode({
      editableForecastType: monthMode.editableForecastType,
      label: `${formatForecastType(params.forecastType)} locked`,
      reason: `Only the ${formatForecastType(monthMode.editableForecastType)} is editable for this month.`
    });
  }

  return monthMode;
}

function dateFor(year: number, month: number, day: number) {
  return new Date(year, month - 1, day);
}

const diagnosticCases: ForecastEntryModeDiagnosticCase[] = [
  {
    name: "past month is read-only",
    params: { year: 2026, month: 4, currentDate: dateFor(2026, 5, 10) },
    expected: { editable: false, editableForecastType: null, locked: true }
  },
  {
    name: "current month through the 15th edits previous-month forecast",
    params: { year: 2026, month: 5, currentDate: dateFor(2026, 5, 15) },
    expected: { editable: true, editableForecastType: "previous_month", locked: false }
  },
  {
    name: "current month after the 15th edits ongoing forecast",
    params: { year: 2026, month: 5, currentDate: dateFor(2026, 5, 16) },
    expected: { editable: true, editableForecastType: "ongoing", locked: false }
  },
  {
    name: "future month edits previous-month forecast",
    params: { year: 2026, month: 6, currentDate: dateFor(2026, 5, 16) },
    expected: { editable: true, editableForecastType: "previous_month", locked: false }
  },
  {
    name: "AI forecast is never editable",
    params: { year: 2026, month: 5, currentDate: dateFor(2026, 5, 10), forecastType: "ai_forecast" },
    expected: { editable: false, editableForecastType: "previous_month", locked: true }
  },
  {
    name: "closed revenue is never editable",
    params: { year: 2026, month: 6, currentDate: dateFor(2026, 5, 16), forecastType: "actuals" },
    expected: { editable: false, editableForecastType: "previous_month", locked: true }
  },
  {
    name: "non-active monthly forecast type is locked",
    params: { year: 2026, month: 5, currentDate: dateFor(2026, 5, 10), forecastType: "ongoing" },
    expected: { editable: false, editableForecastType: "previous_month", locked: true }
  }
];

function serializeParams(params: ForecastEntryModeDiagnosticCase["params"]) {
  return {
    ...params,
    currentDate: params.currentDate.toISOString()
  };
}

function matchesExpectation(actual: ForecastEntryMode, expected: ForecastEntryModeExpectation) {
  return (
    actual.editable === expected.editable &&
    actual.editableForecastType === expected.editableForecastType &&
    actual.locked === expected.locked
  );
}

export function getForecastEntryModeDiagnostics() {
  return diagnosticCases.map((testCase) => {
    const actual = getForecastEntryMode(testCase.params);

    return {
      name: testCase.name,
      params: serializeParams(testCase.params),
      expected: testCase.expected,
      actual,
      passed: matchesExpectation(actual, testCase.expected)
    };
  });
}
